**Import the the packages**

In [29]:
from bs4 import BeautifulSoup
import urllib
import pandas as pd
import re
import requests

# Reference - https://gist.github.com/wassname/5b10774dfcd61cdd3f28

**URL of the website to be scraped**

In [30]:
wiki = 'https://en.wikipedia.org/wiki/Economy_of_the_European_Union'

In [31]:
proxies = {}

In [32]:
response = requests.get(wiki,proxies=proxies)

In [33]:
page_html = response.text
page_soup = BeautifulSoup(page_html,"html.parser")

In [34]:
tables = page_soup.findAll("table", { "class" : "wikitable" })

In [35]:
print ("Number of Tables = " +str(len(tables)))

Number of Tables = 17

In [36]:
table_1 = tables[16]

In [37]:
print(table_1)

<table class="wikitable">
<tbody><tr style="background:#efefef;">
<th rowspan="2">Rank
</th>
<th rowspan="2">NUTS-1 Region
</th>
<th rowspan="2">Member state
</th>
<th colspan="2">GDP per capita (2017)
</th></tr>
<tr style="background:#efefef;">
<th style="width:5em;"><small>in euros</small>
</th>
<th style="width:5em;"><small>As % of EU-28 average</small>
</th></tr>
<tr style="text-align:right;">
<td>1.
</td>
<td><a class="new" href="/w/index.php?title=Severna_i_Iztochna_Bulgaria&amp;action=edit&amp;redlink=1" title="Severna i Iztochna Bulgaria (page does not exist)">Severna i Iztochna Bulgaria</a>
</td>
<td align="left"><small><span class="flagicon"><img alt="" class="thumbborder" data-file-height="600" data-file-width="1000" decoding="async" height="14" src="//upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Bulgaria.svg/23px-Flag_of_Bulgaria.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Bulgaria.svg/35px-Flag_of_Bulgaria.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Bulgaria.svg/46px-Flag_of_Bulgaria.svg.png 2x" width="23"/> </span><a href="/wiki/Bulgaria" title="Bulgaria">Bulgaria</a></small>
</td>
<td><i>11,200</i></td>
<td><i>37%</i>
</td></tr>
<tr style="text-align:right;">
<td>2.
</td>
<td><a class="new" href="/w/index.php?title=Macroregiunea_Doi&amp;action=edit&amp;redlink=1" title="Macroregiunea Doi (page does not exist)">Macroregiunea Doi</a>
</td>
<td align="left"><small><span class="flagicon"><img alt="" class="thumbborder" data-file-height="400" data-file-width="600" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Romania.svg/23px-Flag_of_Romania.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Romania.svg/35px-Flag_of_Romania.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Romania.svg/45px-Flag_of_Romania.svg.png 2x" width="23"/> </span><a href="/wiki/Romania" title="Romania">Romania</a></small>
</td>
<td><i>13,400</i></td>
<td><i>45%</i>
</td></tr>
<tr style="text-align:right;">
<td>3.
</td>
<td><a href="/wiki/Great_Plain_and_North" title="Great Plain and North">Alföld és Észak</a>
</td>
<td align="left"><small><span class="flagicon"><img alt="" class="thumbborder" data-file-height="600" data-file-width="1200" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Flag_of_Hungary.svg/23px-Flag_of_Hungary.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Flag_of_Hungary.svg/35px-Flag_of_Hungary.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Flag_of_Hungary.svg/46px-Flag_of_Hungary.svg.png 2x" width="23"/> </span><a href="/wiki/Hungary" title="Hungary">Hungary</a></small>
</td>
<td><i>13,700</i></td>
<td><i>45%</i>
</td></tr>
<tr style="text-align:right;">
<td>4.
</td>
<td><a class="new" href="/w/index.php?title=Region_Wschodni&amp;action=edit&amp;redlink=1" title="Region Wschodni (page does not exist)">Region Wschodni</a>
</td>
<td align="left"><small><span class="flagicon"><img alt="" class="thumbborder" data-file-height="800" data-file-width="1280" decoding="async" height="14" src="//upload.wikimedia.org/wikipedia/en/thumb/1/12/Flag_of_Poland.svg/23px-Flag_of_Poland.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/1/12/Flag_of_Poland.svg/35px-Flag_of_Poland.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/1/12/Flag_of_Poland.svg/46px-Flag_of_Poland.svg.png 2x" width="23"/> </span><a href="/wiki/Poland" title="Poland">Poland</a></small>
</td>
<td><i>14,600</i></td>
<td><i>49%</i>
</td></tr>
<tr style="text-align:right;">
<td>5.
</td>
<td><a class="mw-redirect" href="/wiki/Voreia_Ellada" title="Voreia Ellada">Voreia Ellada</a>
</td>
<td align="left"><small><span class="flagicon"><img alt="" class="thumbborder" data-file-height="400" data-file-width="600" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Greece.svg/23px-Flag_of_Greece.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Greece.svg/35px-Flag_of_Greece.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Greece.svg/45px-Flag_of_Greece.svg.png 2x" width="23"/> </span><a href="/wiki/Greece" title="Greece">Greece</a></small>
</td>
<td><i>15,600</i></td>
<td><i>52%</i>
</td></tr>
<tr style="text-align:right;">
<td>6.
</td>
<td><a href="/wiki/Kentriki_Ellada" title="Kentriki Ellada">Kentriki Ellada</a>
</td>
<td align="left"><small><span class="flagicon"><img alt="" class="thumbborder" data-file-height="400" data-file-width="600" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Greece.svg/23px-Flag_of_Greece.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Greece.svg/35px-Flag_of_Greece.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Greece.svg/45px-Flag_of_Greece.svg.png 2x" width="23"/> </span><a href="/wiki/Greece" title="Greece">Greece</a></small>
</td>
<td><i>16,600</i></td>
<td><i>55%</i>
</td></tr>
<tr style="text-align:right;">
<td>7.
</td>
<td><a class="new" href="/w/index.php?title=Macroregiunea_Patru&amp;action=edit&amp;redlink=1" title="Macroregiunea Patru (page does not exist)">Macroregiunea Patru</a>
</td>
<td align="left"><small><span class="flagicon"><img alt="" class="thumbborder" data-file-height="400" data-file-width="600" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Romania.svg/23px-Flag_of_Romania.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Romania.svg/35px-Flag_of_Romania.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Romania.svg/45px-Flag_of_Romania.svg.png 2x" width="23"/> </span><a href="/wiki/Romania" title="Romania">Romania</a></small>
</td>
<td><i>16,700</i></td>
<td><i>55%</i>
</td></tr>
<tr style="text-align:right;">
<td>8.
</td>
<td><a href="/wiki/Macroregiunea_Unu" title="Macroregiunea Unu">Macroregiunea Unu</a>
</td>
<td align="left"><small><span class="flagicon"><img alt="" class="thumbborder" data-file-height="400" data-file-width="600" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Romania.svg/23px-Flag_of_Romania.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Romania.svg/35px-Flag_of_Romania.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Romania.svg/45px-Flag_of_Romania.svg.png 2x" width="23"/> </span><a href="/wiki/Romania" title="Romania">Romania</a></small>
</td>
<td><i>17,400</i></td>
<td><i>58%</i>
</td></tr>
<tr style="text-align:right;">
<td>9.
</td>
<td><a href="/wiki/Nisia_Aigaiou,_Kriti" title="Nisia Aigaiou, Kriti">Nisia Aigaiou, Kriti</a>
</td>
<td align="left"><small><span class="flagicon"><img alt="" class="thumbborder" data-file-height="400" data-file-width="600" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Greece.svg/23px-Flag_of_Greece.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Greece.svg/35px-Flag_of_Greece.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Greece.svg/45px-Flag_of_Greece.svg.png 2x" width="23"/> </span><a href="/wiki/Greece" title="Greece">Greece</a></small>
</td>
<td><i>17,900</i></td>
<td><i>60%</i>
</td></tr>
<tr style="text-align:right;">
<td>10.
</td>
<td>Makroregion Centralny
</td>
<td align="left"><small><span class="flagicon"><img alt="" class="thumbborder" data-file-height="800" data-file-width="1280" decoding="async" height="14" src="//upload.wikimedia.org/wikipedia/en/thumb/1/12/Flag_of_Poland.svg/23px-Flag_of_Poland.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/1/12/Flag_of_Poland.svg/35px-Flag_of_Poland.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/1/12/Flag_of_Poland.svg/46px-Flag_of_Poland.svg.png 2x" width="23"/> </span><a href="/wiki/Poland" title="Poland">Poland</a></small>
</td>
<td><i>18,000</i></td>
<td><i>60%</i>
</td></tr>
</tbody></table>

In [38]:
rows=table_1.findAll("tr")
row_lengths=[len(r.findAll(['th','td'])) for r in rows]
ncols=max(row_lengths)
nrows=len(rows)

data=[]
for i in range(nrows):
    rowD=[]
    for j in range(ncols):
        rowD.append('')
    data.append(rowD)

In [39]:
print (len(data))
print (len(data[0]))

12
5

In [40]:
for i in range(len(rows)):
    row=rows[i]
    cells = row.findAll(["td","th"])
    for j in range(len(cells)):
        cell=cells[j]
        data[i][j]+=cell.text

In [41]:
data

[['Rank\n',
  'NUTS-1 Region\n',
  'Member state\n',
  'GDP per capita (2017)\n',
  ''],
 ['in euros\n', 'As\xa0% of EU-28 average\n', '', '', ''],
 ['1.\n',
  'Severna i Iztochna Bulgaria\n',
  '\xa0Bulgaria\n',
  '11,200',
  '37%\n'],
 ['2.\n', 'Macroregiunea Doi\n', '\xa0Romania\n', '13,400', '45%\n'],
 ['3.\n', 'Alföld és Észak\n', '\xa0Hungary\n', '13,700', '45%\n'],
 ['4.\n', 'Region Wschodni\n', '\xa0Poland\n', '14,600', '49%\n'],
 ['5.\n', 'Voreia Ellada\n', '\xa0Greece\n', '15,600', '52%\n'],
 ['6.\n', 'Kentriki Ellada\n', '\xa0Greece\n', '16,600', '55%\n'],
 ['7.\n', 'Macroregiunea Patru\n', '\xa0Romania\n', '16,700', '55%\n'],
 ['8.\n', 'Macroregiunea Unu\n', '\xa0Romania\n', '17,400', '58%\n'],
 ['9.\n', 'Nisia Aigaiou, Kriti\n', '\xa0Greece\n', '17,900', '60%\n'],
 ['10.\n', 'Makroregion Centralny\n', '\xa0Poland\n', '18,000', '60%\n']]

In [42]:
data_cols = data[0]
data = data[1:]

In [43]:
df = pd.DataFrame(data, columns=data_cols)
df

,Rank,NUTS-1 Region,Member state,GDP per capita (2017),
0,in euros\n,As % of EU-28 average\n,,,
1,1.\n,Severna i Iztochna Bulgaria\n,Bulgaria\n,"11,200",37%\n
2,2.\n,Macroregiunea Doi\n,Romania\n,"13,400",45%\n
3,3.\n,Alföld és Észak\n,Hungary\n,"13,700",45%\n
4,4.\n,Region Wschodni\n,Poland\n,"14,600",49%\n
5,5.\n,Voreia Ellada\n,Greece\n,"15,600",52%\n
6,6.\n,Kentriki Ellada\n,Greece\n,"16,600",55%\n
7,7.\n,Macroregiunea Patru\n,Romania\n,"16,700",55%\n
8,8.\n,Macroregiunea Unu\n,Romania\n,"17,400",58%\n
9,9.\n,"Nisia Aigaiou, Kriti\n",Greece\n,"17,900",60%\n
10,10.\n,Makroregion Centralny\n,Poland\n,"18,000",60%\n

In [52]:
def display_table(num):
    rows=tables[num].findAll("tr")
    row_lengths=[len(r.findAll(['th','td'])) for r in rows]
    ncols=max(row_lengths)
    nrows=len(rows)

    data=[]
    for i in range(nrows):
        rowD=[]
        for j in range(ncols):
            rowD.append('')
        data.append(rowD)

    print (len(data))
    print (len(data[0]))

    for i in range(len(rows)):
        row=rows[i]
        cells = row.findAll(["td","th"])
        for j in range(len(cells)):
            cell=cells[j]
            data[i][j]+=cell.text

    data_cols = data[0]
    data = data[1:]

    df = pd.DataFrame(data, columns=data_cols)
    return df

In [58]:
display_table(11)

23
13

,Main trade partners[70],2008,2009,2010,2011,,,,,,,,
0,Exports (million euro)\n,Imports (million euro)\n,Total Trade (million euro)\n,Exports\n,Imports\n,Total Trade\n,Exports\n,Imports\n,Total Trade\n,Exports\n,Imports\n,Total Trade\n,
1,Total EU\n,"1,319,819\n","1,582,932\n","2,902,751\n","1,101,746\n","1,234,317\n","2,336,063\n","1,360,059 \n","1,531,043 \n","2,891,102\n","1,561,890 \n","1,726,514 \n","3,288,404\n"
2,United States\n,"247,818\n","182,351\n","430,169\n","203,587\n","154,862\n","358,449\n","242,451\n","173,067\n","415,518\n","263,791\n","191,555\n","455,346\n"
3,China\n,"78,276\n","247,815\n","326,091\n","82,391\n","214,238\n","296,629\n","113,426\n","282,509\n","395,935\n","136,372\n","293,693\n","430,065\n"
4,Russia\n,"104,843\n","178,294\n","283,137\n","65,587\n","118,122\n","183,709\n","86,134\n","160,709\n","246,843\n","108,355\n","199,922\n","308,277\n"
5,Switzerland\n,"100,537\n","82,348\n","182,885\n","88,693\n","80,570\n","169,263\n","110,401\n","85,228\n","195,629\n","142,022\n","93,202\n","235,224\n"
6,Norway\n,"43,698\n","95,888\n","139,586\n","37,476\n","68,864\n","106,340\n","41,914\n","78,981\n","120,895\n","46,678\n","93,813\n","140,491\n"
7,Japan\n,"42,347\n","76,177\n","118,524\n","35,932\n","58,233\n","94,165\n","43,948\n","67,258\n","111,206\n","49,018\n","69,549\n","118,567\n"
8,Turkey\n,"54,415\n","45,963\n","100,378\n","44,385\n","36,228\n","80,613\n","61,747\n","42,397\n","104,144\n","73,096\n","48,143\n","121,239\n"
9,India\n,"31,349\n","29,540\n","60,889\n","27,477\n","25,414\n","52,891\n","34,866\n","33,308\n","68,112\n","40,558\n","39,906\n","80,464\n"
10,South Korea\n,"25,491\n","39,565\n","65,056\n","21,596\n","32,370\n","53,966\n","27,957\n","39,391\n","67,348\n","32,510\n","36,175\n","68,685\n"
11,Brazil\n,"26,302\n","35,855\n","62,157\n","21,574\n","25,926\n","47,500\n","31,466\n","33,238\n","64,704\n","35,752\n","38,939\n","74,691\n"
12,Canada\n,"25,468\n","25,043\n","50,511\n","21,934\n","19,285\n","41,219\n","26,758\n","24,697\n","51,455\n","29,885\n","30,708\n","60,593\n"
13,Singapore\n,"22,213\n","16,137\n","38,350\n","20,404\n","14,579\n","34,983\n","24,550\n","18,760\n","43,310\n","27,256\n","19,184\n","46,440\n"
14,South Africa\n,"20,800\n","24,597\n","45,397\n","16,083\n","19,229\n","35,312\n","21,755\n","20,406\n","42,161\n","26,212\n","21,807\n","48,019\n"
15,Saudi Arabia\n,"21,081\n","22,001\n","43,082\n","19,068\n","11,766\n","30,834\n","23,216\n","16,300\n","39,516\n","26,401\n","28,440\n","54,841\n"
16,Taiwan\n,"11,595\n","24,069\n","35,660\n","10,021\n","17,875\n","27,896\n","14,782\n","24,138\n","38,920\n","16,212\n","24,230\n","40,532\n"
17,Hong Kong\n,"21,786\n","12,258\n","34,044\n","19,667\n","13,277\n","32,944\n","27,250\n","14,302\n","41,552\n","30,763\n","10,969\n","41,732\n"
18,Australia\n,"26,689\n","13,785\n","40,474\n","21,930\n","9,923\n","31,853\n","26,955\n","12,454\n","39,409\n","31,159\n","14,944\n","46,103\n"
19,Algeria\n,"15,391\n","28,259\n","43,650\n","14,807\n","17,410\n","32,217\n","15,584\n","21,069\n","36,653\n","17,279\n","27,844\n","45,123\n"
20,Libya\n,"5,836\n","35,308\n","41,144\n","6,484\n","20,870\n","27,354\n","7,087\n","29,230\n","36,317\n","2,093\n","10,444\n","12,537\n"
21,Mexico\n,"21,976\n","13,981\n","35,597\n","15,988\n","10,135\n","26,123\n","21,342\n","13,748\n","35,090\n","23,908\n","16,985\n","40,893\n"